insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 206.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 413, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 413, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 413, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 413, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 413, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 280.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MOR MORELIA', 250, 374, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 70, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 140, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 140, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 140, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 140, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 140, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96.75, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96.75, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96.75, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96.75, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 96.75, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TEP TEPIC', 250, 129, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 259.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 519, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 519, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 519, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 519, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 519, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311.25, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311.25, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311.25, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311.25, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 311.25, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 250, 415, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 342, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 684, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 684, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 684, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 684, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 684, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 396, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-PUE PUEBLA', 250, 528, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 435, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 870, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 870, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 870, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 870, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 870, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519.75, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519.75, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519.75, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519.75, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 519.75, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-VRZ VERACRUZ', 250, 693, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 216, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 432, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 432, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 432, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 432, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 432, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 234, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-XAL XALAPA', 250, 312, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COA COATZA MINA', 250, 0, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 193, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 386, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 386, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 386, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 386, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 386, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383.25, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383.25, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383.25, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383.25, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 383.25, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-CUN CANCUN 1', 250, 511, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 149, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 298, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 298, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 298, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 298, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 298, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132.75, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132.75, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132.75, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132.75, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 132.75, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MER MERIDA', 250, 177, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 254.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 509, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 509, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 509, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 509, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 509, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 294, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 294, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 187.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-TUX TUXTLA', 250, 250, '2026-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2024-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2025-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 0, 0, '2025-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2025-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2026-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2026-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2026-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2107, '2026-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('BAJIO', 613, 2312, '2026-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2024-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2025-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 0, 0, '2025-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 4701, '2025-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2025-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2026-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2026-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2026-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 3052, '2026-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('OCCIDENTE', 713, 2842, '2026-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2024-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2025-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 0, 0, '2025-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2025-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('ORIENTE', 613, 1934, '2026-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2024-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2025-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 0, 0, '2025-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-09-01');
