insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2025-12-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-01-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-02-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-03-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-04-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-05-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-06-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-07-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-08-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-09-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-10-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-11-01');
insert into multidistrito_bolsas (region_bolsa, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('SURESTE', 663, 337, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0.25, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 0, 0, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 526.75, 0.25, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-IRA IRAPUATO', 578, 0.25, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 2107, 0.75, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 2107, 1, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1580.25, 0.75, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-LON LEON', 1734, 0.75, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MTY MONTERREY', 0, 0, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 569, 0, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 569, 0, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-AGS AGUASCALIENTES', 0, 0, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 14, 0, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 14, 0, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-COL COLIMA', 0, 0, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 958, 0.246, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 958, 0.246, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GBA GDL BARRANCA', 0, 0.246, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 1142, 0.246, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 1142, 0.246, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GES GDL ESTADIO', 0, 0.246, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 490, 0.246, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 490, 0.246, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 0, 0.246, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 565, 0.246, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 565, 0.246, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-GPR GDL PRIMAVERA', 0, 0.246, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 541, 0.016000000000000014, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 541, 0.016000000000000014, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-MOR MORELIA', 0, 0.016000000000000014, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 422, 0, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 422, 0, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-TEP TEPIC', 0, 0, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 597, 0.053464322647363005, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 597, 0.053464322647363005, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-CBA CORDOBA ORIZABA', 103.40000000000005, 0.053464322647363005, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 389, 0.2, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 389, 0.2, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2025-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-PUE PUEBLA', 386.8, 0.2, '2026-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-05-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-06-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-07-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-08-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-09-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-10-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-11-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2024-12-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2025-01-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 0, 0, '2025-02-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 648, 0.5914167528438469, '2025-03-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 648, 0.5914167528438469, '2025-04-01');
insert into multidistrito_asignacion (distrito, ordenes_asignadas, porcentaje, vigente_desde) values ('CTA-TPI-INT-VRZ VERACRUZ', 1143.8, 0.5914167528438469, '2025-05-01');
