-- supabase/08_seed_ingresos.sql
-- Generado desde ingresos.xlsx (histórico ene-2024 a dic-2026)

insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 475, 4245, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 3755, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4041, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 550, 4140, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 625, 4140, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4140, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4140, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4140, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4140, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4140, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-IRA IRAPUATO', 600, 4050, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 475, 14722, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 13356, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 550, 10650, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 625, 10650, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10650, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10650, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10650, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10650, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10650, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-LON LEON', 600, 10230, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 677.8735632183908, 3828, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 3707, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 2957, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1600, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 1000, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 500, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MTY MONTERREY', 800, 0, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 475, 7429, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 6540, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 6540, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 4148, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 550, 3579, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 625, 3579, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-AGS AGUASCALIENTES', 600, 3579, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 485, 1213, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1119, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1024, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 550, 1010, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 625, 1010, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1010, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1010, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1010, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1010, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COL COLIMA', 600, 1231, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 601.7559739319333, 5524, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 5114, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 650, 4156, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 725, 4156, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GBA GDL BARRANCA', 700, 4156, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 597.676131797482, 7466, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 6865, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 6865, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 6865, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 6865, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 5290, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 650, 4299, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 725, 4299, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4299, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4299, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4299, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4299, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4299, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GES GDL ESTADIO', 700, 4176, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 622.076135147531, 6541, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 6260, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4382, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 4477, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 650, 3987, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 725, 3987, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 700, 3987, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4917, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 5012.5, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 5108, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 5108, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 5108, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 650, 4392, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 725, 4392, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4392, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4392, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4392, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4392, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4392, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 700, 4515, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 475, 3622, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 3209, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 550, 2588, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 675, 2588, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2588, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2588, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2588, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2588, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2588, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MOR MORELIA', 650, 2810, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 485, 1878, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1738, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 550, 1316, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 625, 1316, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1316, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1316, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1316, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1316, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1526, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TEP TEPIC', 600, 1850, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 475, 4267, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3748, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 550, 3001, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 625, 3001, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CBA CORDOBA ORIZABA', 600, 3001, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 475, 4829, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 4145, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 550, 3556, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 625, 3556, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-PUE PUEBLA', 600, 3556, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 475, 8301, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 7431, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 550, 6533, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 625, 6533, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-05-01');
