insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-VRZ VERACRUZ', 600, 6533, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 450, 3218, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2786, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 550, 2286, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 625, 2286, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-XAL XALAPA', 600, 2286, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-COA COATZA MINA', 0, 0, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 450, 4343, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 550, 3957, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 625, 3957, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-CUN CANCUN 1', 600, 3957, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 465, 4633, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 3312, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 625, 2225, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-MER MERIDA', 600, 2225, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 450, 4302, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 4438, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 4438, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 4438, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 4438, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 4438, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 3550, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 3550, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 550, 2848, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 625, 2848, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('PLANTA INTERNA', 'CTA-TPI-INT-TUX TUXTLA', 600, 2848, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 245, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 490, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 490, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 490, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 490, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 490, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 301.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-IRA IRAPUATO', 250, 402, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 683, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1366, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1366, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1366, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1366, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1366, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902.25, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902.25, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902.25, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902.25, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 902.25, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-LON LEON', 250, 1203, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 60.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 121, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 70, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 51, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 36, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 36, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 79, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 79, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 79, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 79, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 59, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-MTY MONTERREY', 250, 0, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 444.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 889, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 889, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 601, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 601, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 601, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 433.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-AGS AGUASCALIENTES', 250, 578, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 47, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 94, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 94, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 94, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 94, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 94, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 108, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 108, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 73.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-COL COLIMA', 250, 98, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 205, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 410, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 410, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 410, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 410, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 410, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314.25, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314.25, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314.25, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314.25, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 314.25, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GBA GDL BARRANCA', 250, 419, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 300.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 601, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 601, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 601, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 601, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 601, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 417, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GES GDL ESTADIO', 250, 556, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 140.5, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 281, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 281, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 281, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 281, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 281, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 583, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 408, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313.5, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313.5, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313.5, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313.5, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 313.5, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GLM GDL LOPEZ MATEOS', 250, 418, '2026-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 116, '2024-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 232, '2024-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 232, '2024-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 232, '2024-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 232, '2024-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 232, '2024-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 514, '2024-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 514, '2024-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 514, '2024-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 514, '2024-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 385, '2024-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2024-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 398.25, '2025-01-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 398.25, '2025-02-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 398.25, '2025-03-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 398.25, '2025-04-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 398.25, '2025-05-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-06-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-07-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-08-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-09-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-10-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-11-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2025-12-01');
insert into poliza_parametros (poliza, distrito, precio_por_orden, ordenes_dimensionadas, vigente_desde) values ('RECOLECCIONES', 'CTA-TPI-INT-GPR GDL PRIMAVERA', 250, 531, '2026-01-01');
